### ISSUE TITLE
Error: Depends on one or more Android Libraries but is a jar 

### ISSUE THREAD

**Issue by jeremy-techson** [Commit451/Easel#7]
`Error:Module 'com.github.Commit451.Easel:easel:2.1.0' depends on one or more Android Libraries but is a jar` when using `2.1.0` but seems OK when using

```groovy
compile 'com.github.Commit451.Easel:easel:2.1.0@aar'
```

**Comment by Jawnnypoo** [comment]
I was seeing this earlier today as well. Not too sure why this is a problem now. I may just need to change the instructions in the README

**Comment by Jawnnypoo** [comment]
Added this to the README. Thanks for pointing it out
